### ISSUE TITLE
Error with example `printTitle(String, int)` function

### ISSUE THREAD

**Issue by tnsolley** [sparkfun/Qwiic_Micro_OLED#3]
Tried using a copy-pasted version of the example-function (see SFE page [here](https://learn.sparkfun.com/tutorials/qwiic-micro-oled-hookup-guide#examples)), I'm getting a compile error in Arduino IDE.
Arduino v. 1.8.8
Windows 10
Compiling for Arduino Nano.
See [here](https://github.com/sparkfun/SparkFun_SSD1320_OLED_Arduino_Library/issues/6) for context of the problem; using the Qwiic Micro OLED, `SFE_MicroOLED.h`, `SSD1320_OLED.h`...

Direct output of Arduino compiler;
....
```
H:\Dev\Cosplay_pictures\Legacy_Mando_SWEU\Helmet\sketch_jan21a\sketch_jan21a.ino: In function 'void loop()':

H:\Dev\Cosplay_pictures\Legacy_Mando_SWEU\Helmet\sketch_jan21a\sketch_jan21a.ino:92:6: note:   initializing argument 1 of 'void printTitle(String, int)'

 void printTitle(String title, int font)

      ^

exit status 1
Error compiling for board Arduino Nano.
```

**Comment by santaimpersonator** [comment]
@tnsolley Is this still an issue?
It looks like you closed the other issue you filed: https://github.com/sparkfun/SparkFun_SSD1320_OLED_Arduino_Library/issues/6

**Comment by santaimpersonator** [comment]
I'll close this for now. Feel free to reopen the issue if needed.
