### ISSUE TITLE
Arduino Library Update

### ISSUE THREAD

**Issue by SFEMark** [sparkfun/Qwiic_Micro_OLED#4]
The Arduino library linked here (https://github.com/sparkfun/Qwiic_Micro_OLED/tree/master/Libraries) is out of date. The Micro_OLED Arduino Library (https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library) has Qwiic examples added as well as some new fixes that help with compile issues for non-AVR boards. Can we get the library link merged with the Micro OLED Arduino Library?

**Comment by nseidle** [comment]
Got it. I removed the old library from this repo. Best to keep software and hardware separate. I've started a separate issue in sparkle to fix the bad link in the tutorial (for Andy to fix).
